<?php if ($block['block-effect']) {
    $this->css($this->assetModule('css/block.css', 'blog'));
} ?>
<div class="news-block">
    <div class="news-item-block itemList clearfix">
        <div class="owl-carousel text-center clearfix hover-captions-container">
            <?php foreach ($block['resources'] as $post) { ?>
                <div class="item hover-captions hover-captions-slide col-sm-12 col-md-12" itemscope
                     itemtype="https://schema.org/Article">
                    <div class="hover-caption">
                        <ul class="list-unstyled">
                            <?php if ($block['showdate']) { ?>
                                <li class="dt-published"><i
                                            class="fa fa-calendar"></i> <?php echo _b('Time'); ?>
                                    : <?php echo $this->escape($post['time_publish_view']); ?></li>
                            <?php } ?>
                            <?php if ($block['showhits']) { ?>
                                <li><i class="fa fa-eye"></i> <?php echo _b('Read'); ?>
                                    : <?php echo _number($this->escape($post['hits'])); ?></li>
                            <?php } ?>
                            <?php if ($block['showauthor']) { ?>
                                <?php foreach ($post['authors'] as $author) { ?>
                                    <li>
                                        <i class="fa fa-user"></i> <?php echo $author['authorRole']; ?> :
                                        <a title="<?php echo $author['authorName']; ?>"
                                           href="<?php echo $author['authorUrl']; ?>">
                                            <?php echo $author['authorName']; ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                        </ul>
                    </div>
                    <a itemprop="url" class="u-url hover-caption-more"
                       title="<?php echo $this->escape($post['title']); ?>"
                       href="<?php echo $this->escape($post['storyUrl']); ?>">
                        <img itemprop="image" class="media-object img-responsive u-photo"
                             src="<?php echo $this->escape($post['thumbUrl']); ?>"
                             alt="<?php echo $this->escape($post['title']); ?>">
                    </a>
                    <h3 itemprop="name headline">
                        <a itemprop="url" class="u-url hover-caption-more"
                           title="<?php echo $this->escape($post['title']); ?>"
                           href="<?php echo $this->escape($post['storyUrl']); ?>">
                            <?php echo $this->escape($post['title']); ?>
                        </a>
                    </h3>
                    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $post['time_publish'])); ?>"/>
                </div>
            <?php } ?>
        </div>
        <?php /* if (!empty($block['resources'])) { ?>
        <div class="recent-post-list clearfix">
            <?php foreach ($block['resources'] as $post) { ?>
                <div class="recent-post-single clearfix h-post" itemprop="liveBlogUpdate" itemscope itemtype="http://schema.org/BlogPosting">
                    <div class="row">
                        <?php if ($post['image'] && $block['show-image']) { ?>
                            <div class="col-md-4">
                                <a itemprop="url" title="<?php echo $this->escape($post['title']); ?>"
                                   href="<?php echo $this->escape($post['postUrl']); ?>">
                                    <img itemprop="image" class="img-responsive img-rounded u-photo"
                                         src="<?php echo $this->escape($post['thumbUrl']); ?>"
                                         alt="<?php echo $this->escape($post['title']); ?>"/>
                                </a>
                            </div>
                        <?php } ?>
                        <div class="<?php if ($post['image'] && $block['show-image']) { ?>col-md-8<?php } else { ?>col-md-12<?php } ?>">
                            <div class="recent-post-single-title p-name" itemprop="name">
                                <h3 class="clearfix" itemprop="headline">
                                    <a itemprop="url" title="<?php echo $this->escape($post['title']); ?>"
                                       href="<?php echo $this->escape($post['postUrl']); ?>">
                                        <?php echo $this->escape($post['title']); ?>
                                    </a>
                                </h3>
                            </div>
                            <div class="recent-post-single-information small">
                                <ul class="clearfix list-inline recent-post-time">
                                    <?php if ($block['show-time']) { ?>
                                    <li><i class="fa fa-clock-o"></i> <?php echo $this->escape($post['time_create_view']); ?></li>
                                    <?php } ?>
                                    <?php if ($block['show-hits']) { ?>
                                    <li><i class="fa fa-eye"></i> <?php echo $this->escape(_number($post['hits'])); ?></li>
                                    <?php } ?>
                                </ul>
                            </div>
                            <?php if (!empty($post['text_summary']) && $block['show-summary']) { ?>
                                <div class="recent-post-single-summery clearfix p-summary" itemprop="articleBody description">
                                    <?php echo $post['text_summary']; ?>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
        <?php if ($block['show-morelink']) { ?>
            <div class="recent-event-more clearfix">
                <a title="<?php echo _b('More posts'); ?>"
                   href="<?php echo $this->escape($block['morelink']); ?>"><?php echo _b('More posts'); ?></a>
            </div>
        <?php } ?>
    <?php } */?>
    </div>
</div>